PRACTISE

In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [17]:
arr1 = np.array(([1,2,3,4,5],[1,2,3,4,5]))
arr2 = np.array(([1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]))

print(arr1)
print('\n')
print(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
data = np.array((([1,2,3,4,5],
                  [1,2,3,4,5],
                  [1,2,3,4,5]),
                  
                  ([1,2,3,4,5],
                   [1,2,3,4,5],
                   [1,2,3,4,5])))
data

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [38]:
arr_1 = np.zeros((5,3,3))
arr_1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
arr_0 = np.ones((3,2,3))
arr_0

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

OPeration


In [59]:
a = np.array([1,2,3,4,5])
print('sum :',np.sum(a))
print('mean:',np.mean(a))
print('median :',np.median(a))
print('Module :',np.mod(a,a))

sum : 15
mean: 3.0
median : 3.0
Module : [0 0 0 0 0]


In [62]:
full = np.full((50,50),7)
print(full)

[[7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 ...
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]]


In [ ]:
full =np.full((10,10),100)
full

In [64]:
arr = np.arange(12)
print("Original Array :", arr)

reshaped = arr.reshape(3,4)
print("Reshaped Array :", reshaped)

flattened = arr.flatten()
print("Flattened Array :", flattened)

raveled = arr.ravel()
print("Raveled Array : ", raveled )

transposed = reshaped.T
print("Transposed Array :", transposed)




Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
