Numpy Python


In [1]:
import numpy as np

Creating numpy -> Array

In [2]:
np_arr = np.array([1,2,3,4,5])
np_arr

array([1, 2, 3, 4, 5])

In [3]:
np_zero = np.zeros((6,6))
np_zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
np_ones = np.ones((5,6))
print("Numpy ones Array : \n", np_ones)

Numpy ones Array : 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


OPERATIONS ON NUMPY ARRAY

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a + b
print("a+b :",c)

a+b : [ 7  9 11 13 15]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a - b
d = b - a
print("a-b :",c)
print("b-a :",d)

a-b : [-3 -3 -3]
b-a : [3 3 3]


In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a*b
print("a * b :",c)


a * b : [ 4 10 18]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

c = a*b*c
print("a * b * c :",c)


a * b * c : [ 28  80 162]


In [9]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
total = np.sum(a)
print(total)

55


In [10]:
np_full = np.full((50,50), 7)
print("Numpy Full Array : \n",np_full)

Numpy Full Array : 
 [[7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 ...
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]]


In [11]:
np_random = np.random.random((3,5)) *100
print("Numpy Random Array :\n ", np_random)

Numpy Random Array :
  [[16.72661616  6.67824527 75.84232799 71.8201996  38.23211328]
 [60.85565838 51.70598423 41.5176389  58.36276503 47.15109715]
 [28.04594781 29.65059131 69.90925112 69.55439446  0.72039851]]


In [12]:
zeros = np.zeros((3,3))
ones = np.ones((3,3))
identity = np.eye(3)
full = np.full((3,3), 5)        
print("Numpy Zeros Array : \n", zeros)
print("Numpy Ones Array : \n", ones)
print("Numpy Identity Array : \n", identity)
print("Numpy Full Array : \n", full)

Numpy Zeros Array : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Numpy Identity Array : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Numpy Full Array : 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [13]:
random = np.random.random((3,3))
print("Numpy Random Array : \n", random)
sequence = np.arange(1, 10, 2)
print("Numpy Sequence Array : \n", sequence)

Numpy Random Array : 
 [[0.93389885 0.4996307  0.60343107]
 [0.89001372 0.42976168 0.49792343]
 [0.68414343 0.71194062 0.20096492]]
Numpy Sequence Array : 
 [1 3 5 7 9]


Vector Matrix and Tensor 




In [14]:
vector = np.array([1, 2, 3])
print("Numpy Vector : \n", vector)

matrix = np.array([[1, 2], [3, 4]])
print("Numpy Matrix : \n", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Numpy Tensor : \n", tensor)



Numpy Vector : 
 [1 2 3]
Numpy Matrix : 
 [[1 2]
 [3 4]]
Numpy Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Reshaping



In [15]:
arr = np.arange(12)
print("Original Array :", arr)

reshaped = arr.reshape(3,4)
print("Reshaped Array :", reshaped)

flattened = arr.flatten()
print("Flattened Array :", flattened)

raveled = arr.ravel()
print("Raveled Array : ", raveled )

transposed = reshaped.T
print("Transposed Array :", transposed)

Original Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
